"""Write audio-src/SOURCES.md: one row per source file (where it came from, who made it, licence,
sha1) and which shipped files use it. Run after fetch.py --lock and build.py.

Usage: python -I sources_md.py
"""
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))
SRC = os.path.dirname(HERE)


def load(name: str) -> dict:
    with open(os.path.join(SRC, name), encoding="utf8") as f:
        return json.load(f)


def main() -> None:
    music = load("music-sources.json")
    sfx = load("sfx-sources.json")
    lock = load("sources.lock.json")
    recipes = load("recipes.json")
    used: dict[str, list[str]] = {}

    def use(sid: str, out: str) -> None:
        used.setdefault(sid, []).append(out)

    for name, r in recipes["instruments"].items():
        items = list(r["zones"].items()) if "zones" in r else [(str(i), s) for i, s in enumerate(r["hits"])]
        for key, sid in items:
            use(sid, f"inst/{name}-{key}.mp3")
    for cue, r in recipes["sfx"].items():
        for i, parts in enumerate(r["variants"]):
            for p in parts:
                use(p["src"], f"sfx/{cue}-{i + 1}.mp3")
    for name, r in recipes["ambience"].items():
        if r["mode"] == "loop":
            use(r["src"], f"amb/{name}.mp3")
        else:
            for i, p in enumerate(r["shots"]):
                use(p["src"], f"amb/{name}-{i + 1}.mp3")

    out = [
        "# Audio sources",
        "",
        "Generated by `audio-src/tools/sources_md.py` from `music-sources.json`, `sfx-sources.json`,",
        "`sources.lock.json` and `recipes.json`. Every licence below was read on the source page itself",
        "(GitHub LICENSE file for VSCO 2 CE and VCSL; the asset page for Kenney and OpenGameArt). No file was",
        "ripped from a game; no NC, ND or share-alike licences. `audio-src/tools/fetch.py` downloads exactly",
        "these files and checks the sha1s; `build.py` turns them into `public/assets/audio/`.",
        "",
        "## Instrument samples (music)",
        "",
        "Repository files at a pinned commit. VSCO 2 CE: recorded by Sam Gossner and Simon Dalzell, sample",
        "cutting by Elan Hickler (Soundemote), published by Versilian Studios. VCSL: Versilian Community",
        "Sample Library by Sam Gossner / Versilian Studios. Both CC0 1.0. Versilian asks that the samples not",
        "be sold as a sample library and that credit be given; we only ship processed notes inside the game,",
        "and credit them in ASSETS.md.",
        "",
        "| id | repository @ commit | path | licence | sha1 | ships as |",
        "|---|---|---|---|---|---|",
    ]
    for sid, e in music.items():
        repo = e["page"].replace("https://github.com/", "")
        out.append(
            f"| {sid} | [{repo}]({e['page']}) @ {e['commit'][:10]} | `{e['path']}` | {e['licence']} |"
            f" {lock.get(sid, {}).get('sha1', '?')[:12]} | {', '.join(used.get(sid, ['(unused)']))} |"
        )
    out += [
        "",
        "## Sound effects and ambience",
        "",
        "| id | page | author | pack / archive member | licence | sha1 | ships as |",
        "|---|---|---|---|---|---|---|",
    ]
    for sid, e in sfx.items():
        member = f"`{e['member']}` in `{e['url'].rsplit('/', 1)[-1]}`" if "member" in e else f"`{e['url'].rsplit('/', 1)[-1]}`"
        note = f" ({e['note']})" if "note" in e else ""
        out.append(
            f"| {sid} | [{e['pack']}]({e['page']}) | {e['author']}{note} | {member} | {e['licence']} |"
            f" {lock.get(sid, {}).get('sha1', '?')[:12]} | {', '.join(sorted(set(used.get(sid, ['(unused)']))))} |"
        )
    out.append("")
    with open(os.path.join(SRC, "SOURCES.md"), "w", encoding="utf8", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote SOURCES.md")


if __name__ == "__main__":
    main()
