// Prints every texture key/frame the game draws (src/art/manifest.ts, derived from data) to
// agents/out/art-manifest.md, with whether a packed atlas supplies it or it falls back to generated art.
// Usage: node art-src/tools/manifest.mjs
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { runnerImport } from 'vite';

const { module: m } = await runnerImport('/src/art/manifest.ts', {
  configFile: false,
  logLevel: 'error',
});
const entries = m.artManifest();

const frames = new Map();
for (const a of Object.values(m.ATLAS_FILES)) {
  const p = `public/${a.json}`;
  if (!existsSync(p)) continue;
  const json = JSON.parse(readFileSync(p, 'utf8'));
  for (const [name, f] of Object.entries(json.frames))
    frames.set(name, { atlas: a.key, ...f.frame });
}
const tileset = existsSync(`public/${m.TILESET_FILE}`);

const status = (e) => {
  if (e.group === 'tiles') return tileset ? 'art (tileset)' : 'generated';
  const f = frames.get(m.atlasFrameName(e));
  if (f) return `art (${f.atlas} ${f.w}x${f.h})`;
  return e.optional ? 'optional, none yet' : 'generated';
};

const groups = ['tiles', 'world', 'ui', 'chars'];
let md = `# Art manifest\n\nGenerated by \`node art-src/tools/manifest.mjs\` from \`src/art/manifest.ts\` (keys come from the data files, so new items,\ncrops or placeables appear here automatically). Do not edit by hand.\n\n`;
const done = entries.filter((e) => status(e).startsWith('art')).length;
md += `Total: **${entries.length}** keys/frames; **${done}** supplied by art, **${entries.length - done}** fall back to generated placeholders or (optional decor/landmarks) are not drawn yet.\n\n`;
md += `Atlases: tiles = \`public/${m.TILESET_FILE}\` (strip, tile order = Tiled gid - 1); `;
md += Object.entries(m.ATLAS_FILES)
  .map(([g, a]) => `${g} = \`public/${a.png}\``)
  .join(', ');
md += `.\nSingle-image keys are atlas frames named by the key; frames of multi-frame textures (\`tiles_placeholder\`, \`player\`, \`crops\`, \`npc_*\`) are atlas frames named by the frame.\n\n`;
for (const g of groups) {
  const list = entries.filter((e) => e.group === g);
  md += `## ${g} (${list.length})\n\n| texture | frame | size | exact | kind | from | status |\n|---|---|---|---|---|---|---|\n`;
  for (const e of list)
    md += `| \`${e.texture}\` | ${e.frame ? `\`${e.frame}\`` : ''} | ${e.w}x${e.h} | ${e.exact ? 'yes' : 'min'} | ${e.kind} | ${e.from} | ${status(e)} |\n`;
  md += '\n';
}
writeFileSync('agents/out/art-manifest.md', md);
console.log(`art-manifest.md: ${entries.length} entries, ${done} with art`);
