import { createHash } from 'node:crypto';
import { readFileSync, readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

/** Every file under a directory, as forward-slash paths relative to it. */
function walk(dir, root = dir) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }
  return entries.flatMap((name) => {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) return walk(full, root);
    return name.startsWith('.') ? [] : [relative(root, full).split('\\').join('/')];
  });
}

/** Files under this folder of public/ get their own long-lived cache, one entry per file version. */
const AUDIO_DIR = 'assets/audio/';

/**
 * Emits `sw.js`: a tiny offline-first service worker. It precaches every built asset plus the
 * files in public/, serves cache-first, and drops old caches when the content hash changes.
 * Offline play is a store requirement (the game is a static bundle, so it costs nothing).
 *
 * Audio (about 2 MB) is kept apart in `tiny-acre-audio`, which survives releases: each file is
 * stored under its path plus a hash of its content, a new version downloads only the files whose
 * hash changed (or that are new), and activation deletes entries no longer listed.
 */
/** @param {string} [publicDir] @returns {import('vite').Plugin} */
export function offlineServiceWorker(publicDir = 'public') {
  return {
    name: 'tiny-acre-offline-sw',
    apply: 'build',
    generateBundle(_options, bundle) {
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: serviceWorkerSource(Object.keys(bundle), publicDir) });
    },
  };
}

/** The sw.js text for a build (exported for tests). @param {string[]} built @param {string} publicDir */
export function serviceWorkerSource(built, publicDir) {
  const publicFiles = walk(publicDir).filter((f) => f !== 'sw.js');
  const files = [...new Set([...built, ...publicFiles])].sort();
  const audio = Object.fromEntries(
    files
      .filter((f) => f.startsWith(AUDIO_DIR))
      .map((f) => [f, createHash('sha1').update(readFileSync(join(publicDir, f))).digest('hex').slice(0, 10)]),
  );
  const rest = files.filter((f) => !(f in audio));
  const sizes = rest
    .filter((f) => publicFiles.includes(f))
    .map((f) => statSync(join(publicDir, f)).size)
    .join(',');
  const version = createHash('sha1')
    .update(rest.join('|') + sizes)
    .digest('hex')
    .slice(0, 10);
  const precache = [...new Set(['./', './index.html', ...rest.map((f) => `./${f}`)])];
  return `// Generated by the build. Do not edit.
const CACHE = 'tiny-acre-${version}';
const AUDIO_CACHE = 'tiny-acre-audio';
const PRECACHE = ${JSON.stringify(precache, null, 2)};
/** Audio file (relative to the scope) -> content hash. */
const AUDIO = ${JSON.stringify(audio, null, 2)};

const scope = () => self.registration.scope;
const audioKey = (path) => new URL(path + '?v=' + AUDIO[path], scope()).href;
/** The audio path a request is for, or null. */
function audioPath(url) {
  const u = new URL(url);
  const base = new URL(scope());
  if (u.origin !== base.origin || !u.pathname.startsWith(base.pathname)) return null;
  const path = u.pathname.slice(base.pathname.length);
  return Object.prototype.hasOwnProperty.call(AUDIO, path) ? path : null;
}

/** Download only the audio files whose current version is not cached yet. */
async function cacheAudio() {
  const cache = await caches.open(AUDIO_CACHE);
  const have = new Set((await cache.keys()).map((r) => r.url));
  await Promise.all(
    Object.keys(AUDIO).map(async (path) => {
      const key = audioKey(path);
      if (have.has(key)) return;
      const res = await fetch(new URL(path, scope()).href, { cache: 'no-cache' });
      if (!res.ok) throw new Error('audio ' + path + ' ' + res.status);
      await cache.put(key, res);
    }),
  );
}

/** Drop audio entries that are not the current version of a listed file. */
async function pruneAudio() {
  const cache = await caches.open(AUDIO_CACHE);
  const keep = new Set(Object.keys(AUDIO).map(audioKey));
  await Promise.all((await cache.keys()).filter((r) => !keep.has(r.url)).map((r) => cache.delete(r)));
}

self.addEventListener('install', (event) => {
  event.waitUntil(
    Promise.all([caches.open(CACHE).then((c) => c.addAll(PRECACHE)), cacheAudio()]).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) =>
        Promise.all(
          keys.filter((k) => k.startsWith('tiny-acre-') && k !== CACHE && k !== AUDIO_CACHE).map((k) => caches.delete(k)),
        ),
      )
      .then(pruneAudio)
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  const path = audioPath(req.url);
  if (path) {
    event.respondWith(
      caches.open(AUDIO_CACHE).then((c) =>
        c.match(audioKey(path)).then(
          (hit) =>
            hit ||
            fetch(req).then((res) => {
              if (res.ok) c.put(audioKey(path), res.clone());
              return res;
            }),
        ),
      ),
    );
    return;
  }
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(req)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
            }
            return res;
          })
          .catch(() => (req.mode === 'navigate' ? caches.match('./') : Response.error())),
    ),
  );
});
`;
}
