import { createHash } from 'node:crypto';
import { readdirSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';

/** Every file under a directory, as forward-slash paths relative to it. */
function walk(dir, root = dir) {
  let entries;
  try {
    entries = readdirSync(dir);
  } catch {
    return [];
  }
  return entries.flatMap((name) => {
    const full = join(dir, name);
    if (statSync(full).isDirectory()) return walk(full, root);
    return name.startsWith('.') ? [] : [relative(root, full).split('\\').join('/')];
  });
}

/**
 * Emits `sw.js`: a tiny offline-first service worker. It precaches every built asset plus the
 * files in public/, serves cache-first, and drops old caches when the content hash changes.
 * Offline play is a store requirement (the game is a static bundle, so it costs nothing).
 */
/** @param {string} [publicDir] @returns {import('vite').Plugin} */
export function offlineServiceWorker(publicDir = 'public') {
  return {
    name: 'tiny-acre-offline-sw',
    apply: 'build',
    generateBundle(_options, bundle) {
      const built = Object.keys(bundle);
      const publicFiles = walk(publicDir).filter((f) => f !== 'sw.js');
      const files = [...new Set([...built, ...publicFiles])].sort();
      const sizes = publicFiles.map((f) => statSync(join(publicDir, f)).size).join(',');
      const version = createHash('sha1')
        .update(files.join('|') + sizes)
        .digest('hex')
        .slice(0, 10);
      const precache = [...new Set(['./', './index.html', ...files.map((f) => `./${f}`)])];
      this.emitFile({
        type: 'asset',
        fileName: 'sw.js',
        source: `// Generated by the build. Do not edit.
const CACHE = 'tiny-acre-${version}';
const PRECACHE = ${JSON.stringify(precache, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('tiny-acre-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const req = event.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  event.respondWith(
    caches.match(req, { ignoreSearch: true }).then(
      (hit) =>
        hit ||
        fetch(req)
          .then((res) => {
            if (res.ok) {
              const copy = res.clone();
              caches.open(CACHE).then((c) => c.put(req, copy));
            }
            return res;
          })
          .catch(() => (req.mode === 'navigate' ? caches.match('./') : Response.error())),
    ),
  );
});
`,
      });
    },
  };
}
